import { v4 as uuidv4 } from "uuid";

import { IModuleDTO } from "../dtos/ModuleDTO";

const modules: IModuleDTO[] = [
  {
    id: uuidv4(),
    name: "Dashboard",
    url: "/dashboard",
    icon: "dashboard",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
    subModules: [],
  },
  {
    id: uuidv4(),
    name: "Atendimentos",
    url: "/tickets",
    icon: "call",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 1,
    subModules: [],
  },
  {
    id: uuidv4(),
    name: "Contatos",
    url: "/contact",
    icon: "contact",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
    subModules: [],
  },
  {
    id: uuidv4(),
    name: "Campanhas",
    url: "/campaign",
    icon: "campaign",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
    subModules: [],
  },
  {
    id: uuidv4(),
    name: "Relatórios",
    url: "/report",
    icon: "report",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
    subModules: [],
  },
  {
    id: uuidv4(),
    name: "Google Agenda",
    url: "/googleagenda",
    icon: "calendar",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
    subModules: [],
  },
  {
    id: uuidv4(),
    name: "Chat Shop",
    url: "/chatshop",
    icon: "chatshop",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 10,
    subModules: [
      {
        id: uuidv4(),
        name: "Pedidos",
        url: "/chatshop/request",
        icon: "request",
        global: false,
        admin: false,
        selected: false,
        open: false,
        badge: 0,
      },
      {
        id: uuidv4(),
        name: "Gerenciador",
        url: "/chatshop/manager",
        icon: "manager",
        global: false,
        admin: false,
        selected: false,
        open: false,
        badge: 0,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Administração",
    url: "/admin",
    icon: "config",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
    subModules: [],
  },
];

export default modules;
