import { IFieldDTO } from "../dtos/IFieldDTO";

export default [
  {
    name: "Autocomplete",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Editor",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Input",
    component: true,
    test: true,
    responsive: true,
    dark: true,
  },
  {
    name: "Password",
    component: true,
    test: false,
    responsive: true,
    dark: true,
  },
  {
    name: "Switch",
    component: true,
    test: true,
    responsive: true,
    dark: true,
  },
  {
    name: "Checkbox",
    component: true,
    test: true,
    responsive: true,
    dark: true,
  },
  {
    name: "Radio",
    component: true,
    test: true,
    responsive: true,
    dark: true,
  },
  {
    name: "Colors",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Date",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Select",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Breadcrumb",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "ButtonDefault",
    component: true,
    test: true,
    responsive: true,
    dark: true,
  },
  {
    name: "ButtonIcon",
    component: true,
    test: true,
    responsive: true,
    dark: true,
  },
  {
    name: "Link",
    component: true,
    test: true,
    responsive: true,
    dark: true,
  },
  {
    name: "Dropdown",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Typograph",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Title",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Tooltip",
    component: true,
    test: false,
    responsive: false,
    dark: true,
  },
  {
    name: "Table",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Skeleton",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Modal",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Loading",
    component: true,
    test: true,
    responsive: true,
    dark: true,
  },
  {
    name: "Divider",
    component: true,
    test: false,
    responsive: true,
    dark: true,
  },
  {
    name: "Card",
    component: false,
    test: false,
    responsive: false,
    dark: false,
  },
  {
    name: "Icon",
    component: true,
    test: true,
    responsive: true,
    dark: true,
  },
  {
    name: "Toast",
    component: true,
    test: false,
    responsive: true,
    dark: true,
  },
] as IFieldDTO[];
