export default [
  {
    id: 1,
    name: "Eike Sousa 1",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "eike.sousa@hotmail.com",
    profile: "Administrador",
    color: " #25B733",
    active: true,
  },
  {
    id: 2,
    name: "Matheus Santos 2",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "matheus.santos@greenchat.com",
    profile: "Administrador",
    color: "#0080FF",
    active: true,
  },
  {
    id: 3,
    name: "Rodrigo Souza 3",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    color: "#D3A3F9",
    active: false,
  },
  {
    id: 4,
    name: "Rodrigo Souza 4",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    active: true,
  },
  {
    id: 5,
    name: "Thiago Reis 5",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "thiago.reis@hotmail.com",
    profile: "Administrador",
    color: " #25B733",
    active: false,
  },
  {
    id: 6,
    name: "Eike Sousa 6",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "eike.sousa@hotmail.com",
    profile: "Administrador",
    active: true,
  },
  {
    id: 7,
    name: "Matheus Santos 7",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "matheus.santos@greenchat.com",
    profile: "Administrador",
    color: "#0080FF",
    active: false,
  },
  {
    id: 8,
    name: "Rodrigo Souza 8",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    color: "#D3A3F9",
    active: true,
  },
  {
    id: 9,
    name: "Rodrigo Souza 9",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    color: " #25B733",
    active: false,
  },
  {
    id: 10,
    name: "Thiago Reis 10",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "thiago.reis@hotmail.com",
    profile: "Administrador",
    active: true,
  },
  {
    id: 11,
    name: "Eike Sousa 11",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "eike.sousa@hotmail.com",
    profile: "Administrador",
    color: " #25B733",
    active: true,
  },
  {
    id: 12,
    name: "Matheus Santos 12",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "matheus.santos@greenchat.com",
    profile: "Administrador",
    color: "#D3A3F9",
    active: false,
  },
  {
    id: 13,
    name: "Rodrigo Souza 13",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    active: true,
  },
  {
    id: 14,
    name: "Rodrigo Souza 14",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    active: false,
  },
  {
    id: 15,
    name: "Thiago Reis 15",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "thiago.reis@hotmail.com",
    profile: "Administrador",
    color: " #25B733",
    active: true,
  },

  {
    id: 16,
    name: "Eike Sousa 16",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "eike.sousa@hotmail.com",
    profile: "Administrador",
    color: "#0080FF",
    active: true,
  },
  {
    id: 17,
    name: "Matheus Santos 17",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "matheus.santos@greenchat.com",
    profile: "Administrador",
    active: false,
  },
  {
    id: 18,
    name: "Rodrigo Souza 18",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    color: "#D3A3F9",
    active: true,
  },
  {
    id: 19,
    name: "Rodrigo Souza 19",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    color: " #25B733",
    active: true,
  },
  {
    id: 20,
    name: "Thiago Reis 20",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "thiago.reis@hotmail.com",
    profile: "Administrador",
    active: true,
  },
  {
    id: 21,
    name: "Eike Sousa 21",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "eike.sousa@hotmail.com",
    profile: "Administrador",
    color: "#0080FF",
    active: false,
  },
  {
    id: 22,
    name: "Matheus Santos 22",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "matheus.santos@greenchat.com",
    profile: "Administrador",
    active: true,
  },
  {
    id: 23,
    name: "Rodrigo Souza 23",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    active: false,
  },
  {
    id: 24,
    name: "Rodrigo Souza 24",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    color: " #25B733",
    active: false,
  },
  {
    id: 25,
    name: "Thiago Reis 25",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "thiago.reis@hotmail.com",
    profile: "Administrador",
    color: "#0080FF",
    active: false,
  },
  {
    id: 26,
    name: "Eike Sousa 26",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "eike.sousa@hotmail.com",
    profile: "Administrador",
    color: "#D3A3F9",
    active: true,
  },
  {
    id: 27,
    name: "Matheus Santos 27",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "matheus.santos@greenchat.com",
    profile: "Administrador",
    color: " #25B733",
    active: false,
  },
  {
    id: 28,
    name: "Rodrigo Souza 28",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    active: true,
  },
  {
    id: 29,
    name: "Rodrigo Souza 29",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "rodrigo.souza@hotmail.com",
    profile: "Administrador",
    color: "#0080FF",
    active: false,
  },
  {
    id: 30,
    name: "Thiago Reis 30",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/108px-Unknown_person.jpg?20200423155822",
    email: "thiago.reis@hotmail.com",
    profile: "Administrador",
    color: " #25B733",
    active: false,
  },
] as IDataTableDTO[];

interface IDataTableDTO {
  id: number;
  name: string;
  url: string;
  email: string;
  profile: string;
  color?: string;
  active: boolean;
}
