import { v4 as uuidv4 } from "uuid";

import { IModuleDTO } from "../Sidebar/dtos/ModuleDTO";

const modules: IModuleDTO[] = [
  {
    id: uuidv4(),
    name: "Dashboard",
    url: "/dashboard",
    icon: "dashboard",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
  },
  {
    id: uuidv4(),
    name: "Atendimentos",
    url: "/tickets",
    icon: "call",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 1,
  },
  {
    id: uuidv4(),
    name: "Contatos",
    url: "/contacts",
    icon: "contact",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
  },
  {
    id: uuidv4(),
    name: "Campanhas",
    url: "/campaigns",
    icon: "campaign",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
  },
  {
    id: uuidv4(),
    name: "Relatórios",
    url: "/reports",
    icon: "report",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
  },
  {
    id: uuidv4(),
    name: "Google Agenda",
    url: "/googlecalendar",
    icon: "calendar",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
  },
  {
    id: uuidv4(),
    name: "Chat Shop",
    url: "/chatshop",
    icon: "chatshop",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 10,
  },
  {
    id: uuidv4(),
    name: "Administração",
    url: "/administration",
    icon: "config",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
  },
  {
    id: uuidv4(),
    name: "Design",
    url: "/design",
    icon: "painting",
    global: false,
    admin: false,
    selected: false,
    open: false,
    badge: 0,
  },
];

export default modules;
