import { SVGProps } from "react";

export type IIconDTO =
  | "alert"
  | "arrowdown"
  | "arrowleft"
  | "arrowright"
  | "arrowup"
  | "asterisk"
  | "attachfile"
  | "bug"
  | "calendar"
  | "call"
  | "campaign"
  | "chatbot"
  | "chatshop"
  | "check"
  | "close"
  | "components"
  | "config"
  | "connections"
  | "contact"
  | "dark"
  | "dashboard"
  | "delete"
  | "edit"
  | "email"
  | "eye"
  | "eyeslash"
  | "facebook"
  | "fast"
  | "filter"
  | "fullscreen"
  | "help"
  | "ia"
  | "info"
  | "instagram"
  | "integrations"
  | "light"
  | "logout"
  | "manager"
  | "menu"
  | "menufold"
  | "menuunfold"
  | "modules"
  | "notification"
  | "painting"
  | "password"
  | "profile"
  | "profilegroup"
  | "queues"
  | "report"
  | "request"
  | "satisfaction"
  | "search"
  | "send"
  | "success"
  | "suport"
  | "tags"
  | "telegram"
  | "users"
  | "volumedown"
  | "volumemute"
  | "volumeup"
  | "warning"
  | "whatsapp";

export interface IIconRootProps extends SVGProps<SVGSVGElement> {
  icon: IIconDTO;
  datatestid?: string | null;
}

export interface ISVGProps extends SVGProps<SVGSVGElement> {
  datatestid?: string | null;
}
